name = "jaredraylaw"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "jaredraylaw-db"
database_id = "ebbf5ac5-5be0-4320-8e56-c9646e69b995"

[site]
bucket = "./public"