name = "jaredraylawcom"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "jaredraylaw-db"
database_id = "5028a850-3b1a-4731-aeba-4449a256d94d"

[site]
bucket = "./public"
